name: 🏁 Auto-Close Completed Milestones
on:
  schedule:
    - cron: "0 18 * * FRI"   # Runs every Friday at 18:00 UTC (end of sprint)
  workflow_dispatch:          # Allows manual trigger from GitHub UI

jobs:
  close:
    name: Close Finished Milestones
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Check and Close Completed Milestones
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // List all open milestones
            const milestones = await github.rest.issues.listMilestones({
              owner,
              repo,
              state: "open"
            });

            if (milestones.data.length === 0) {
              console.log("No open milestones found.");
              return;
            }

            for (const m of milestones.data) {
              console.log(`🔍 Checking milestone: ${m.title}`);

              // Get open issues for this milestone
              const openIssues = await github.paginate(
                github.rest.issues.listForRepo,
                { owner, repo, milestone: m.number, state: "open" }
              );

              if (openIssues.length === 0) {
                // Close milestone when all issues are done
                await github.rest.issues.updateMilestone({
                  owner,
                  repo,
                  milestone_number: m.number,
                  state: "closed"
                });

                console.log(`✅ Milestone "${m.title}" closed automatically.`);
              } else {
                console.log(`⏳ Milestone "${m.title}" still has ${openIssues.length} open issue(s).`);
              }
            }
